parameters:
    telegram_bot_username: '%env(TELEGRAM_BOT_USERNAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CardStickerService:
        arguments:
            $botUsername: '%telegram_bot_username%'
            $botToken: '%env(TELEGRAM_BOT_TOKEN)%'
            $projectDir: '%kernel.project_dir%'

    App\Service\GameMessageService:
        arguments:
            $botUsername: '%telegram_bot_username%'
